### ISSUE TITLE
release 2.0 and 3.0

### ISSUE THREAD

**Issue by arhimede** [dotkernel/dot-geoip#2]
2.0 will use laminas and composer version < 2

3.0 will use latest laminas and dot-console with composer 2

**Comment by Calin23** [comment]
Update Status 👍 
- Version 2.0 will use an older version of the composer to support compatibility with older systems that are not compatible with version 2 composer.
- Version 3.0 is ready to run on systems that are compatible with composer 2.0.

A tip before installing dot-geoip, if the current system uses dot-console < 3.0 allready it must first be upgraded to a higher version, in case of dot-geoip 2.0 will use dot-console 3.0.2, and in case of dot-geoip it will use the latest version of dot-console, replace "use ZF \ Console \ Route;" with "use Dot \ Console \ RouteCollector as Route;" throughout the system. You can see more here [dot-console](https://github.com/dotkernel/dot-console).
