### ISSUE TITLE
Automation of GeoIp database update

### ISSUE THREAD

**Issue by arhimede** [dotkernel/dot-geoip#3]
check how to  automatize the update of geoip database 
maybe with an API token or something 

add instructions about how to create a monthly cronjob

**Comment by arhimede** [comment]
@alexmerlin does it work with geoip2/geoip2?

**Comment by alexmerlin** [comment]
> 
> 
> @alexmerlin does it work with geoip2/geoip2?

`geoip2/geoip2` is required because it contains `GeoIp2\Database\Reader` necessary for reading the database files.
